name: kaggle-s6e2
channels:
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - alembic=1.18.3=pyhcf101f3_0
  - anyio=4.10.0=py313h06a4308_0
  - aom=3.12.1=h7934f7d_0
  - argon2-cffi=25.1.0=py313h06a4308_0
  - argon2-cffi-bindings=25.1.0=py313hee96239_0
  - asttokens=3.0.0=py313h06a4308_0
  - async-lru=2.0.5=py313h06a4308_0
  - atk-1.0=2.38.0=h04ea711_2
  - attrs=25.4.0=py313h06a4308_2
  - babel=2.17.0=py313h06a4308_0
  - beautifulsoup4=4.14.3=py313h06a4308_0
  - blas=1.0=mkl
  - bleach=6.3.0=py313h06a4308_0
  - bottleneck=1.4.2=py313haa0f9ac_1
  - brotlicffi=1.2.0.0=py313h7354ed3_0
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2026.1.4=hbd8a1cb_0
  - cairo=1.18.4=h44eff21_0
  - catboost=1.2.8=cuda120_py313h974e093_106
  - certifi=2026.01.04=py313h06a4308_0
  - cffi=2.0.0=py313h4eded50_1
  - charset-normalizer=3.4.4=py313h06a4308_0
  - colorlog=6.10.1=pyh707e725_0
  - comm=0.2.3=py313h06a4308_0
  - contourpy=1.3.3=py313hdb19cb5_0
  - cuda-cudart=12.9.79=h5888daf_0
  - cuda-cudart_linux-64=12.9.79=h3f2d84a_0
  - cuda-version=12.9=h4f385c5_3
  - cycler=0.12.1=py313h06a4308_0
  - cyrus-sasl=2.1.28=h83b0a09_4
  - dav1d=1.2.1=h5eee18b_0
  - debugpy=1.8.16=py313hbdd6827_1
  - decorator=5.2.1=py313h06a4308_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - executing=2.2.1=py313h06a4308_0
  - expat=2.7.4=h7354ed3_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h2c49b7f_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=hc364b38_1
  - fonttools=4.61.0=py313h47b2149_0
  - freetype=2.14.1=hf5b9546_0
  - fribidi=1.0.16=h9fb5f84_0
  - gdk-pixbuf=2.42.10=h64b468e_2
  - giflib=5.2.2=hd590300_0
  - glib=2.86.3=h617169b_0
  - glib-tools=2.86.3=h9fad118_0
  - graphite2=1.3.14=h295c915_1
  - graphviz=9.0.0=h78e8752_1
  - greenlet=3.3.1=py313h5d5ffb9_1
  - gtk2=2.24.33=h280cfa0_4
  - gts=0.7.6=h977cf35_4
  - h11=0.16.0=py313h06a4308_1
  - harfbuzz=12.3.0=h79d275a_1
  - html5lib=1.1=pyhd3eb1b0_0
  - httpcore=1.0.9=py313h06a4308_0
  - httpx=0.28.1=py313h06a4308_1
  - icu=73.1=h6a678d5_0
  - idna=3.11=py313h06a4308_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - intel-openmp=2025.0.0=h06a4308_1171
  - ipykernel=6.31.0=py313h7040dfc_0
  - ipython=9.7.0=py313h06a4308_0
  - ipython_pygments_lexers=1.1.1=py313h06a4308_0
  - ipywidgets=8.1.7=py313h06a4308_0
  - jedi=0.19.2=py313h06a4308_0
  - jinja2=3.1.6=py313h06a4308_0
  - joblib=1.5.3=py313h06a4308_0
  - jpeg=9f=h5ce9db8_0
  - json5=0.12.1=py313h06a4308_0
  - jsonschema=4.25.1=py313h06a4308_0
  - jsonschema-specifications=2025.9.1=py313h06a4308_0
  - jupyter=1.1.1=py313h06a4308_0
  - jupyter-lsp=2.3.0=py313h06a4308_0
  - jupyter_client=8.8.0=py313h06a4308_0
  - jupyter_console=6.6.3=py313h06a4308_1
  - jupyter_core=5.9.1=py313h06a4308_0
  - jupyter_events=0.12.0=py313h06a4308_1
  - jupyter_server=2.17.0=py313h06a4308_1
  - jupyter_server_terminals=0.5.4=py313h06a4308_0
  - jupyterlab=4.5.3=py313h06a4308_1
  - jupyterlab_pygments=0.3.0=py313h06a4308_0
  - jupyterlab_server=2.28.0=py313h06a4308_1
  - jupyterlab_widgets=3.0.16=py313h06a4308_0
  - kiwisolver=1.4.9=py313h24d9097_0
  - lcms2=2.17=heab6991_0
  - ld_impl_linux-64=2.44=h153f514_2
  - lerc=4.0.0=h6a678d5_0
  - libavif=1.3.0=h3539ee5_0
  - libboost=1.88.0=h9d9b81f_0
  - libcups=2.4.15=hbe4054b_0
  - libdeflate=1.22=h5eee18b_0
  - libdrm=2.4.124=h5eee18b_0
  - libegl=1.7.0=h5eee18b_2
  - libevent=2.1.12=hdbd6064_1
  - libexpat=2.7.4=h7354ed3_0
  - libffi=3.4.4=h6a678d5_1
  - libfreetype=2.14.1=ha770c72_0
  - libfreetype6=2.14.1=h73754d4_0
  - libgcc=15.2.0=h69a1729_7
  - libgcc-ng=15.2.0=h166f726_7
  - libgd=2.3.3=h536bbd8_4
  - libgfortran=15.2.0=h166f726_7
  - libgfortran-ng=15.2.0=h166f726_7
  - libgfortran5=15.2.0=hc633d37_7
  - libgl=1.7.0=h5eee18b_2
  - libglib=2.86.3=h8b17d9a_0
  - libglvnd=1.7.0=h5eee18b_2
  - libglx=1.7.0=h5eee18b_2
  - libgomp=15.2.0=h4751f2c_7
  - libhwloc=2.12.1=default_hf1bbc79_1000
  - libiconv=1.16=h5eee18b_3
  - libkrb5=1.22.1=h6d2bf13_0
  - liblightgbm=4.6.0=cpu_hc154d20_7
  - libllvm15=15.0.7=he89c38a_4
  - libmpdec=4.0.0=h5eee18b_0
  - libopengl=1.7.0=h5eee18b_2
  - libopenjpeg=2.5.4=hee96239_1
  - libpciaccess=0.18=h5eee18b_0
  - libpng=1.6.54=hee55ce4_0
  - libpq=17.6=h5ca1609_1
  - librsvg=2.58.0=hadf69e7_1
  - libsodium=1.0.20=heac8642_0
  - libstdcxx=15.2.0=h39759b7_7
  - libstdcxx-ng=15.2.0=hc03a8fd_7
  - libtiff=4.7.1=h029b1ac_0
  - libuuid=1.41.5=h5eee18b_0
  - libwebp=1.6.0=h089d785_0
  - libwebp-base=1.6.0=hb7bb969_0
  - libxcb=1.17.0=h9b100fa_0
  - libxgboost=3.1.3=cuda129_h54c741a_0
  - libxkbcommon=1.9.1=h69220b7_0
  - libxml2=2.13.9=h2c43086_0
  - libzlib=1.3.1=hb25bd0a_0
  - lightgbm=4.6.0=cpu_py_ha6cb263_7
  - lmdb=0.9.31=hb25bd0a_0
  - lz4-c=1.9.4=h6a678d5_1
  - mako=1.3.10=pyhcf101f3_1
  - markupsafe=3.0.2=py313h5eee18b_0
  - matplotlib=3.10.8=py313h06a4308_0
  - matplotlib-base=3.10.8=py313h8a257da_0
  - matplotlib-inline=0.2.1=py313h06a4308_0
  - mesalib=25.1.5=h31e3550_0
  - mistune=3.1.2=py313h06a4308_0
  - mkl=2025.0.0=hacee8c2_941
  - mkl-service=2.5.2=py313hacdc0fc_0
  - mkl_fft=2.1.1=py313h57662e1_0
  - mkl_random=1.3.0=py313h23c847b_0
  - mysql-common=9.3.0=h9e076cb_4
  - mysql-libs=9.3.0=h6ecde68_4
  - narwhals=2.16.0=pyhcf101f3_0
  - nbclient=0.10.2=py313h06a4308_0
  - nbconvert=7.16.6=py313h06a4308_0
  - nbconvert-core=7.16.6=py313h06a4308_0
  - nbconvert-pandoc=7.16.6=py313h06a4308_0
  - nbformat=5.10.4=py313h06a4308_0
  - nccl=2.29.2.1=h4d09622_2
  - ncurses=6.5=h7934f7d_0
  - nest-asyncio=1.6.0=py313h06a4308_0
  - notebook=7.5.3=py313h06a4308_0
  - notebook-shim=0.2.4=py313h06a4308_1
  - numexpr=2.14.1=py313h41d4191_0
  - numpy=2.4.1=py313h08c6c3d_0
  - numpy-base=2.4.1=py313h00548fb_0
  - ocl-icd=2.3.3=hb9d3cd8_0
  - opencl-headers=2025.06.13=h5888daf_0
  - openldap=2.6.10=he9288cc_1
  - openssl=3.6.1=h35e630c_1
  - optuna=4.7.0=pyhd8ed1ab_0
  - packaging=25.0=py313h06a4308_1
  - pandas=2.3.3=py313h23c847b_1
  - pandoc=3.8=h06a4308_0
  - pandocfilters=1.5.1=py313h06a4308_0
  - pango=1.56.4=hadf4263_0
  - parso=0.8.5=py313h06a4308_0
  - pcre2=10.46=hf426167_0
  - pexpect=4.9.0=py313h06a4308_1
  - pillow=12.1.0=py313hd9fd23a_0
  - pip=25.3=pyhc872135_0
  - pixman=0.46.4=h7934f7d_0
  - platformdirs=4.5.0=py313h06a4308_0
  - plotly=6.5.2=pyhd8ed1ab_0
  - prometheus_client=0.21.1=py313h06a4308_0
  - prompt-toolkit=3.0.52=py313h06a4308_1
  - prompt_toolkit=3.0.52=hd3eb1b0_1
  - psutil=7.0.0=py313hee96239_1
  - pthread-stubs=0.3=h0ce48e5_1
  - ptyprocess=0.7.0=pyhd3eb1b0_3
  - pure_eval=0.2.3=py313h06a4308_0
  - py-xgboost=3.1.3=cuda129_pyha75543c_0
  - pycparser=2.23=py313h06a4308_0
  - pygments=2.19.2=py313h06a4308_0
  - pyparsing=3.2.5=py313h06a4308_0
  - pyqt=6.9.1=py313hc79087c_0
  - pyqt6-sip=13.10.2=py313hee96239_0
  - pysocks=1.7.1=py313h06a4308_1
  - python=3.13.11=hcf712cf_100_cp313
  - python-dateutil=2.9.0post0=py313h06a4308_2
  - python-fastjsonschema=2.21.2=py313h06a4308_0
  - python-graphviz=0.21=pyhbacfb6d_0
  - python-json-logger=4.0.0=py313h06a4308_0
  - python-tzdata=2025.3=pyhd3eb1b0_0
  - python_abi=3.13=3_cp313
  - pytz=2025.2=py313h06a4308_0
  - pyyaml=6.0.3=py313h591646f_0
  - pyzmq=27.1.0=py313hcf8288c_1
  - qtbase=6.9.2=h1fa0d2d_6
  - qtconsole=5.7.0=py313h06a4308_0
  - qtdeclarative=6.9.2=h55666de_1
  - qtpy=2.4.3=py313h06a4308_0
  - qtsvg=6.9.2=h75a08ff_1
  - qttools=6.9.2=hc856bc8_1
  - qtwayland=6.9.2=h9f1b7ec_1
  - qtwebchannel=6.9.2=hbdd6827_1
  - qtwebsockets=6.9.2=hbdd6827_1
  - readline=8.3=hc2a1206_0
  - referencing=0.37.0=py313h06a4308_0
  - requests=2.32.5=py313h06a4308_1
  - rfc3339-validator=0.1.4=py313h06a4308_0
  - rfc3986-validator=0.1.1=py313h06a4308_0
  - rpds-py=0.28.0=py313h498d7c9_0
  - scikit-learn=1.8.0=py313h86c3e14_0
  - scipy=1.16.3=py313h33bc11c_0
  - seaborn=0.13.2=py313h06a4308_3
  - send2trash=1.8.3=py313h06a4308_0
  - setuptools=80.10.2=py313h06a4308_0
  - sip=6.12.0=py313h7934f7d_0
  - six=1.17.0=py313h06a4308_0
  - sniffio=1.3.1=py313h06a4308_0
  - soupsieve=2.5=py313h06a4308_0
  - spirv-tools=2025.1=hdb19cb5_0
  - sqlalchemy=2.0.46=py313h54dd161_1
  - sqlite=3.51.1=he0a8d7e_0
  - stack_data=0.6.3=py313h06a4308_0
  - tbb=2022.3.0=h698db13_0
  - tbb-devel=2022.3.0=h698db13_0
  - terminado=0.18.1=py313h06a4308_1
  - threadpoolctl=3.5.0=py313h7040dfc_1
  - tinycss2=1.4.0=py313h06a4308_0
  - tk=8.6.15=h54e0aa7_0
  - tomli=2.4.0=pyhcf101f3_0
  - tornado=6.5.4=py313h47b2149_0
  - tqdm=4.67.3=pyh8f84b5b_0
  - traitlets=5.14.3=py313h06a4308_0
  - typing-extensions=4.15.0=py313h06a4308_0
  - typing_extensions=4.15.0=py313h06a4308_0
  - tzdata=2025c=he532380_0
  - urllib3=2.6.3=py313h06a4308_0
  - wayland=1.24.0=hdac8c69_0
  - wcwidth=0.2.14=py313h06a4308_0
  - webencodings=0.5.1=py313h06a4308_2
  - websocket-client=1.8.0=py313h06a4308_0
  - wheel=0.46.3=py313h06a4308_0
  - widgetsnbextension=4.0.14=py313h06a4308_0
  - xcb-util=0.4.1=h5eee18b_2
  - xcb-util-cursor=0.1.5=h5eee18b_0
  - xcb-util-image=0.4.0=h5eee18b_2
  - xcb-util-keysyms=0.4.1=h5eee18b_0
  - xcb-util-renderutil=0.3.10=h5eee18b_0
  - xcb-util-wm=0.4.2=h5eee18b_0
  - xgboost=3.1.3=cuda129_pyh5c66634_0
  - xkeyboard-config=2.44=h382ed1a_1
  - xorg-libice=1.1.2=h9b100fa_0
  - xorg-libsm=1.2.6=h9b100fa_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-libxext=1.3.6=h9b100fa_0
  - xorg-libxfixes=6.0.1=h9b100fa_0
  - xorg-libxrandr=1.5.4=h9b100fa_0
  - xorg-libxrender=0.9.12=h9b100fa_0
  - xorg-libxshmfence=1.3.3=h9b100fa_0
  - xorg-libxxf86vm=1.1.6=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - yaml=0.2.5=h7b6447c_0
  - zeromq=4.3.5=hb0a5e54_1
  - zipp=3.23.0=pyhcf101f3_1
  - zlib=1.3.1=hb25bd0a_0
  - zstd=1.5.7=h11fc155_0
  - pip:
      - kaggle==1.8.4
      - kagglesdk==0.1.15
      - protobuf==6.33.5
      - python-slugify==8.0.4
      - text-unidecode==1.3
prefix: /home/mikej/anaconda3/envs/kaggle-s6e2
